name: req-intel
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - sentence-transformers
    - transformers
    - scikit-learn
    - onnxruntime
    - huggingface-hub
